function dW_da4 = dW_da4(in1,in2)
%dW_da4
%    dW_da4 = dW_da4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Aug-2026 23:09:39

dW_da4 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
end
