function dW_da3 = dW_da3(in1,in2)
%dW_da3
%    dW_da3 = dW_da3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Feb-2026 11:14:48

dW_da3 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
end
