function dW_da2 = dW_da2(in1,in2)
%dW_da2
%    dW_da2 = dW_da2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Feb-2026 21:37:36

dW_da2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
end
