function dW_da1 = dW_da1(in1,in2)
%dW_da1
%    dW_da1 = dW_da1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    24-Feb-2026 11:14:47

dW_da1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
end
