/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * dW_dxi_fcn1.c
 *
 * Code generation for function 'dW_dxi_fcn1'
 *
 */

/* Include files */
#include "dW_dxi_fcn1.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <emmintrin.h>

/* Variable Definitions */
static emlrtRSInfo bc_emlrtRSI = {
    2,                                                       /* lineNo */
    "dW_dxi_fcn1",                                           /* fcnName */
    "C:\\ACXIS Code\\CCM\\planarquad\\metric\\dW_dxi_fcn1.m" /* pathName */
};

static emlrtBCInfo h_emlrtBCI = {
    -1,                                                   /* iFirst */
    -1,                                                   /* iLast */
    9,                                                    /* lineNo */
    10,                                                   /* colNo */
    "in1",                                                /* aName */
    "dW_dphi",                                            /* fName */
    "C:\\ACXIS Code\\CCM\\planarquad\\metric\\dW_dphi.m", /* pName */
    0                                                     /* checkKind */
};

static emlrtBCInfo i_emlrtBCI = {
    -1,                                                   /* iFirst */
    -1,                                                   /* iLast */
    8,                                                    /* lineNo */
    10,                                                   /* colNo */
    "in1",                                                /* aName */
    "dW_dphi",                                            /* fName */
    "C:\\ACXIS Code\\CCM\\planarquad\\metric\\dW_dphi.m", /* pName */
    0                                                     /* checkKind */
};

/* Function Definitions */
void dW_dxi_fcn1(const emlrtStack *sp, real_T i, const real_T x_data[],
                 int32_T x_size, real_T dW_dxi[36])
{
  emlrtStack st;
  real_T c_a[36];
  real_T b_dW_dxi_tmp;
  real_T b_t110_tmp;
  real_T c_dW_dxi_tmp;
  real_T dW_dxi_tmp;
  real_T d_dW_dxi_tmp;
  real_T e_dW_dxi_tmp;
  real_T f_dW_dxi_tmp;
  real_T g_dW_dxi_tmp;
  real_T h_dW_dxi_tmp;
  real_T i_dW_dxi_tmp;
  real_T t103_tmp;
  real_T t110_tmp;
  real_T t2_tmp;
  real_T t3_tmp;
  real_T t4_tmp;
  real_T t5_tmp;
  int32_T b_i;
  boolean_T a;
  boolean_T b_a;
  st.prev = sp;
  st.tls = sp->tls;
  a = (i == 3.0);
  st.site = &bc_emlrtRSI;
  /* dW_dphi */
  /*     dW_dphi = dW_dphi(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     27-Oct-2025 10:39:16 */
  if (x_size < 3) {
    emlrtDynamicBoundsCheckR2012b(3, 1, x_size, &i_emlrtBCI, &st);
  }
  if (x_size < 4) {
    emlrtDynamicBoundsCheckR2012b(4, 1, 3, &h_emlrtBCI, &st);
  }
  t2_tmp = x_data[2] * x_data[2];
  t3_tmp = muDoubleScalarPower(x_data[2], 3.0);
  t4_tmp = x_data[3] * x_data[3];
  t5_tmp = muDoubleScalarPower(x_data[3], 3.0);
  t103_tmp = x_data[2] * x_data[3];
  t110_tmp = t4_tmp * x_data[2];
  b_t110_tmp = t2_tmp * x_data[3];
  b_a = (i == 4.0);
  /* dW_dvx */
  /*     dW_dvx = dW_dvx(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 24.2.
   */
  /*     27-Oct-2025 10:39:18 */
  dW_dxi[0] =
      (real_T)a *
      (((((t3_tmp * -0.28913998242162908 - t5_tmp * 0.0026227128801096429) +
          x_data[2] * 0.08617160390285733) +
         x_data[3] * 0.0087644358336993848) -
        b_t110_tmp * 0.086272098292969973) +
       t110_tmp * -0.01737254026394414);
  dW_dxi_tmp =
      (real_T)a *
      (((-(t103_tmp * 0.0041501974810221921) + t2_tmp * 0.0285433751118621) -
        t4_tmp * 0.000556974996550309) -
       0.022109455593165239);
  dW_dxi[1] = dW_dxi_tmp;
  b_dW_dxi_tmp = (real_T)a * (((((x_data[2] * 0.091043393454827953 -
                                  x_data[3] * 0.0057367205094836842) +
                                 t3_tmp * 0.0015814924093375149) +
                                b_t110_tmp * 0.01080743498559328) -
                               t5_tmp * 0.00059513827575020212) -
                              t110_tmp * 0.0004641720601686834);
  dW_dxi[2] = b_dW_dxi_tmp;
  c_dW_dxi_tmp =
      (real_T)a *
      (((((x_data[2] * 1.0489901067351439 + x_data[3] * 0.068613074725744558) +
          t3_tmp * 0.15654261153496379) -
         b_t110_tmp * 0.052119812851119017) +
        t110_tmp * 0.0063536925143887219) -
       t5_tmp * 1.4348481326211149E-5);
  dW_dxi[3] = c_dW_dxi_tmp;
  d_dW_dxi_tmp =
      (real_T)a *
      (((-(t103_tmp * 0.2200907699127119) - t4_tmp * 0.01063451110311813) -
        t2_tmp * 0.39467326427477017) +
       1.037953691572463);
  dW_dxi[4] = d_dW_dxi_tmp;
  e_dW_dxi_tmp =
      (real_T)a *
      (((((x_data[3] * 0.125519562212039 + x_data[2] * 0.61944325567035829) -
          t3_tmp * 0.30092877942328278) -
         b_t110_tmp * 0.1441480353372272) -
        t5_tmp * 0.0036353654135911542) +
       t110_tmp * 0.0002004047299931539);
  dW_dxi[5] = e_dW_dxi_tmp;
  dW_dxi[6] = dW_dxi_tmp;
  dW_dxi[7] =
      (real_T)a *
      (((((t3_tmp * 0.0082135953996167535 - t5_tmp * 0.0038234714165108629) +
          x_data[2] * 0.0109050081326172) -
         x_data[3] * 0.02077130679920566) -
        b_t110_tmp * 0.039399622412706073) +
       t110_tmp * -0.001004368308671538);
  dW_dxi_tmp =
      (real_T)a *
      (((t103_tmp * 0.0034063341469282179 + t4_tmp * 0.0041644014892153513) +
        t2_tmp * 0.012690370224629479) -
       0.01411359830838531);
  dW_dxi[8] = dW_dxi_tmp;
  f_dW_dxi_tmp =
      (real_T)a *
      (((t103_tmp * 0.1068373129053819 + t2_tmp * 0.30450375941319763) +
        t4_tmp * 0.014726828522148089) -
       0.45766821004635821);
  dW_dxi[9] = f_dW_dxi_tmp;
  g_dW_dxi_tmp =
      (real_T)a *
      (((((x_data[2] * 0.61429363160553141 + x_data[3] * 0.037354544055986469) +
          t3_tmp * 0.16345478742117481) +
         t110_tmp * 0.024454939799985559) -
        t5_tmp * 0.003353135806369892) -
       b_t110_tmp * 0.03291279891859903);
  dW_dxi[10] = g_dW_dxi_tmp;
  h_dW_dxi_tmp =
      (real_T)a *
      (((t103_tmp * 0.0273201366822279 + t2_tmp * 0.27963467626740712) -
        t4_tmp * 0.0013044462198639421) -
       0.18916467432257189);
  dW_dxi[11] = h_dW_dxi_tmp;
  dW_dxi[12] = b_dW_dxi_tmp;
  dW_dxi[13] = dW_dxi_tmp;
  dW_dxi[14] =
      (real_T)a *
      (((((t3_tmp * 0.0019986446984098139 - t5_tmp * 0.0001028562692237775) -
          x_data[2] * 0.017250436959700449) -
         x_data[3] * 0.0133856244512918) +
        b_t110_tmp * 0.0015414215839783839) +
       t110_tmp * -0.0014995214654556751);
  dW_dxi_tmp = (real_T)a * (((((-(x_data[2] * 0.1668544593064758) +
                                b_t110_tmp * 0.0063023155683612766) -
                               x_data[3] * 0.0476446327203229) -
                              t3_tmp * 0.01189270065620298) -
                             t110_tmp * 0.004555275628530712) +
                            t5_tmp * 1.41508144194634E-5);
  dW_dxi[15] = dW_dxi_tmp;
  b_dW_dxi_tmp =
      (real_T)a *
      (((-(t103_tmp * 0.01615194805437483) + t4_tmp * 0.0026443561879822539) +
        t2_tmp * 0.010832936919729631) -
       0.002063012754343378);
  dW_dxi[16] = b_dW_dxi_tmp;
  i_dW_dxi_tmp =
      (real_T)a *
      (((((x_data[3] * 0.028114374355143971 + x_data[2] * 0.01359108666584595) -
          t3_tmp * 0.073220615923823465) -
         t110_tmp * 0.001199053620666533) -
        t5_tmp * 0.00056638010676680645) +
       b_t110_tmp * 0.02060365840520164);
  dW_dxi[17] = i_dW_dxi_tmp;
  dW_dxi[18] = c_dW_dxi_tmp;
  dW_dxi[19] = f_dW_dxi_tmp;
  dW_dxi[20] = dW_dxi_tmp;
  dW_dxi[21] =
      (real_T)a *
      (((((t3_tmp * -0.0094726830364702461 - t5_tmp * 0.0042205592010402231) -
          x_data[2] * 1.215655599599601) -
         x_data[3] * 0.34678533800680761) +
        b_t110_tmp * 0.076216363526516534) +
       t110_tmp * 0.015373978641827841);
  dW_dxi_tmp =
      (real_T)a *
      (((t103_tmp * 0.16988750652949769 + t4_tmp * 0.031931005436878393) +
        t2_tmp * 0.1463322730951255) -
       0.4270078340613826);
  dW_dxi[22] = dW_dxi_tmp;
  c_dW_dxi_tmp = (real_T)a * (((((-(x_data[2] * 0.2478344345087368) -
                                  x_data[3] * 0.041646674026038777) +
                                 t3_tmp * 0.38938293293796777) -
                                t110_tmp * 0.0194927657874763) +
                               b_t110_tmp * 0.12651355683019549) -
                              t5_tmp * 0.002851821903243477);
  dW_dxi[23] = c_dW_dxi_tmp;
  dW_dxi[24] = d_dW_dxi_tmp;
  dW_dxi[25] = g_dW_dxi_tmp;
  dW_dxi[26] = b_dW_dxi_tmp;
  dW_dxi[27] = dW_dxi_tmp;
  dW_dxi[28] =
      (real_T)a *
      (((((t3_tmp * -0.039145762813130758 + t5_tmp * 0.0041586774722428216) +
          x_data[2] * 0.41216332879497952) -
         x_data[3] * 0.019250249788079082) -
        b_t110_tmp * 0.0387863517452484) +
       t110_tmp * 0.16659179256778539);
  dW_dxi_tmp =
      (real_T)a *
      (((t2_tmp * 0.51214750220109728 - t103_tmp * 0.03198457766222456) -
        t4_tmp * 0.02469880072491519) -
       0.24322573369105541);
  dW_dxi[29] = dW_dxi_tmp;
  dW_dxi[30] = e_dW_dxi_tmp;
  dW_dxi[31] = h_dW_dxi_tmp;
  dW_dxi[32] = i_dW_dxi_tmp;
  dW_dxi[33] = c_dW_dxi_tmp;
  dW_dxi[34] = dW_dxi_tmp;
  dW_dxi[35] =
      (real_T)a *
      (((((t3_tmp * 0.1235428240297909 - t5_tmp * 0.004479186719035016) -
          x_data[2] * 0.53678735965388225) +
         x_data[3] * 0.035836304768684983) +
        b_t110_tmp * 0.04028585513692156) +
       t110_tmp * -0.01306494239950848);
  c_a[0] = (real_T)b_a *
           (((((t3_tmp * -0.02875736609765666 - t5_tmp * 3.02582889201592E-5) +
               x_data[2] * 0.0087644358336993848) -
              x_data[3] * 0.01222577179271272) -
             b_t110_tmp * 0.01737254026394414) +
            t110_tmp * -0.007868138640328929);
  dW_dxi_tmp =
      (real_T)b_a *
      (((-(t103_tmp * 0.0011139499931006179) - t2_tmp * 0.0020750987405110961) -
        t4_tmp * 0.001091457224945216) +
       0.006519550058519348);
  c_a[1] = dW_dxi_tmp;
  b_dW_dxi_tmp = (real_T)b_a * (((((x_data[3] * 0.001926800499699499 -
                                    x_data[2] * 0.0057367205094836842) +
                                   t3_tmp * 0.0036024783285310948) +
                                  t5_tmp * 0.00029053938033332221) -
                                 b_t110_tmp * 0.0004641720601686834) -
                                t110_tmp * 0.001785414827250606);
  c_a[2] = b_dW_dxi_tmp;
  c_dW_dxi_tmp =
      (real_T)b_a *
      (((((x_data[2] * 0.068613074725744558 + t5_tmp * 0.00068135231290618326) +
          x_data[3] * 0.0092540587654532016) -
         t3_tmp * 0.017373270950373009) +
        b_t110_tmp * 0.0063536925143887219) -
       t110_tmp * 4.3045443978633438E-5);
  c_a[3] = c_dW_dxi_tmp;
  d_dW_dxi_tmp =
      (real_T)b_a *
      (((-(t2_tmp * 0.110045384956356) - t103_tmp * 0.021269022206236259) +
        t4_tmp * 0.00017380520940634759) +
       0.069199975986572029);
  c_a[4] = d_dW_dxi_tmp;
  e_dW_dxi_tmp =
      (real_T)b_a *
      (((((x_data[2] * 0.125519562212039 - x_data[3] * 0.012361874662250459) -
          t3_tmp * 0.048049345112409082) -
         t5_tmp * 0.001741249490251304) -
        t110_tmp * 0.010906096240773461) +
       b_t110_tmp * 0.0002004047299931539);
  c_a[5] = e_dW_dxi_tmp;
  c_a[6] = dW_dxi_tmp;
  c_a[7] =
      (real_T)b_a *
      (((((t3_tmp * -0.01313320747090202 + t5_tmp * 0.0013856082163272751) -
          x_data[2] * 0.02077130679920566) +
         x_data[3] * 0.0047766179554744456) -
        b_t110_tmp * 0.001004368308671538) +
       t110_tmp * -0.011470414249532591);
  dW_dxi_tmp =
      (real_T)b_a *
      (((t103_tmp * 0.0083288029784307025 + t2_tmp * 0.0017031670734641089) -
        t4_tmp * 0.0011986720448258961) -
       0.0063868283176334419);
  c_a[8] = dW_dxi_tmp;
  f_dW_dxi_tmp =
      (real_T)b_a *
      (((t103_tmp * 0.029453657044296179 + t2_tmp * 0.053418656452690942) -
        t4_tmp * 0.000683913597203622) -
       0.025759012398115039);
  c_a[9] = f_dW_dxi_tmp;
  g_dW_dxi_tmp =
      (real_T)b_a *
      (((((x_data[2] * 0.037354544055986469 + x_data[3] * 0.01369036921932708) -
          t3_tmp * 0.010970932972866341) +
         b_t110_tmp * 0.024454939799985559) -
        t5_tmp * 0.00061276193339582382) -
       t110_tmp * 0.01005940741910968);
  c_a[10] = g_dW_dxi_tmp;
  h_dW_dxi_tmp =
      (real_T)b_a *
      (((-(t103_tmp * 0.0026088924397278828) + t2_tmp * 0.01366006834111395) +
        t4_tmp * 0.0012550212772217571) -
       0.0078698368590162486);
  c_a[11] = h_dW_dxi_tmp;
  c_a[12] = b_dW_dxi_tmp;
  c_a[13] = dW_dxi_tmp;
  c_a[14] =
      (real_T)b_a *
      (((((t3_tmp * 0.00051380719465946121 + t5_tmp * 0.0002369300550340405) -
          x_data[2] * 0.0133856244512918) +
         x_data[3] * 0.0017260362078780479) -
        b_t110_tmp * 0.0014995214654556751) +
       t110_tmp * -0.00030856880767133238);
  dW_dxi_tmp =
      (real_T)b_a *
      (((((t3_tmp * 0.0021007718561204258 + x_data[3] * 0.005838379300381457) -
          x_data[2] * 0.0476446327203229) +
         t5_tmp * 0.00034469779528297092) -
        b_t110_tmp * 0.004555275628530712) +
       t110_tmp * 4.2452443258390211E-5);
  c_a[15] = dW_dxi_tmp;
  b_dW_dxi_tmp =
      (real_T)b_a *
      (((t103_tmp * 0.005288712375964507 - t2_tmp * 0.0080759740271874169) -
        t4_tmp * 0.00037114513132177038) -
       0.049824419577708758);
  c_a[16] = b_dW_dxi_tmp;
  i_dW_dxi_tmp =
      (real_T)b_a *
      (((((x_data[2] * 0.028114374355143971 + t3_tmp * 0.0068678861350672128) -
          x_data[3] * 0.00035198066401409658) -
         t5_tmp * 0.00029750629853403669) -
        b_t110_tmp * 0.001199053620666533) -
       t110_tmp * 0.001699140320300419);
  c_a[17] = i_dW_dxi_tmp;
  c_a[18] = c_dW_dxi_tmp;
  c_a[19] = f_dW_dxi_tmp;
  c_a[20] = dW_dxi_tmp;
  c_a[21] =
      (real_T)b_a *
      (((((t3_tmp * 0.02540545450883884 + t5_tmp * 0.00071528200720821268) -
          x_data[2] * 0.34678533800680761) +
         x_data[3] * 0.01131586280079911) +
        b_t110_tmp * 0.015373978641827841) +
       t110_tmp * -0.012661677603120669);
  dW_dxi_tmp =
      (real_T)b_a *
      (((t103_tmp * 0.063862010873756772 + t2_tmp * 0.084943753264748845) -
        t4_tmp * 0.01487972834290152) -
       0.20359730059381839);
  c_a[22] = dW_dxi_tmp;
  c_dW_dxi_tmp = (real_T)b_a * (((((-(x_data[2] * 0.041646674026038777) -
                                    x_data[3] * 0.020389214455614091) +
                                   t3_tmp * 0.042171185610065172) -
                                  b_t110_tmp * 0.0194927657874763) +
                                 t5_tmp * 0.00030086145252179009) -
                                t110_tmp * 0.00855546570973043);
  c_a[23] = c_dW_dxi_tmp;
  c_a[24] = d_dW_dxi_tmp;
  c_a[25] = g_dW_dxi_tmp;
  c_a[26] = b_dW_dxi_tmp;
  c_a[27] = dW_dxi_tmp;
  c_a[28] =
      (real_T)b_a *
      (((((t3_tmp * -0.0129287839150828 + t5_tmp * 0.0001991521359716541) -
          x_data[2] * 0.019250249788079082) -
         x_data[3] * 0.077150912449677519) +
        b_t110_tmp * 0.16659179256778539) +
       t110_tmp * 0.012476032416728469);
  dW_dxi_tmp =
      (real_T)b_a *
      (((-(t103_tmp * 0.049397601449830381) - t2_tmp * 0.01599228883111228) -
        t4_tmp * 0.032063462910014079) +
       0.038453575318674153);
  c_a[29] = dW_dxi_tmp;
  c_a[30] = e_dW_dxi_tmp;
  c_a[31] = h_dW_dxi_tmp;
  c_a[32] = i_dW_dxi_tmp;
  c_a[33] = c_dW_dxi_tmp;
  c_a[34] = dW_dxi_tmp;
  c_a[35] = (real_T)b_a *
            (((((t3_tmp * 0.01342861837897385 - t5_tmp * 0.00419784421754858) +
                x_data[2] * 0.035836304768684983) +
               x_data[3] * 0.00155648437762456) -
              b_t110_tmp * 0.01306494239950848) +
             t110_tmp * -0.013437560157105051);
  for (b_i = 0; b_i <= 34; b_i += 2) {
    __m128d r;
    __m128d r1;
    r = _mm_loadu_pd(&dW_dxi[b_i]);
    r1 = _mm_loadu_pd(&c_a[b_i]);
    _mm_storeu_pd(&dW_dxi[b_i], _mm_add_pd(r, r1));
  }
}

/* End of code generation (dW_dxi_fcn1.c) */
